package com.kingkharnivore.chefesque.ui.screen.editrecipe

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.kingkharnivore.chefesque.data.local.entity.IngredientEntity
import com.kingkharnivore.chefesque.data.local.entity.RecipeEntity
import com.kingkharnivore.chefesque.data.local.entity.RecipeIngredientEntity
import com.kingkharnivore.chefesque.data.local.entity.RecipeStepEntity
import com.kingkharnivore.chefesque.data.local.entity.StepIngredientLinkEntity
import com.kingkharnivore.chefesque.data.repository.IngredientRepository
import com.kingkharnivore.chefesque.data.repository.RecipeRepository
import com.kingkharnivore.chefesque.domain.model.RecipeType
import com.kingkharnivore.chefesque.ui.screen.addrecipe.IngredientInputState
import com.kingkharnivore.chefesque.ui.screen.addrecipe.StepInputState
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

private const val IngredientSuggestionLimit = 8

data class EditRecipeUiState(
    val isLoading: Boolean = true, val isSaving: Boolean = false, val notFound: Boolean = false, val recipeId: String = "",
    val title: String = "", val description: String = "", val servings: String = "", val prepTimeMinutes: String = "", val cookTimeMinutes: String = "", val recipeType: RecipeType = RecipeType.FULL_DISH, val notes: String = "",
    val ingredients: List<IngredientInputState> = emptyList(), val steps: List<StepInputState> = emptyList(),
    val titleError: String? = null, val servingsError: String? = null, val prepTimeError: String? = null, val cookTimeError: String? = null, val ingredientError: String? = null, val stepError: String? = null, val saveError: String? = null,
    val hasUnsavedChanges: Boolean = false, val saved: Boolean = false,
)

class EditRecipeViewModel(private val recipeId: String, private val recipeRepository: RecipeRepository, private val ingredientRepository: IngredientRepository) : ViewModel() {
    private val _uiState = MutableStateFlow(EditRecipeUiState(recipeId = recipeId)); val uiState: StateFlow<EditRecipeUiState> = _uiState.asStateFlow()
    private val searchJobs = mutableMapOf<String, Job>(); private var originalRecipe: RecipeEntity? = null; private var originalStepsById: Map<String, RecipeStepEntity> = emptyMap()
    init { loadRecipeGraph() }

    private fun loadRecipeGraph() = viewModelScope.launch { runCatching {
        val recipe = recipeRepository.getRecipe(recipeId); if (recipe == null || recipe.archivedAt != null) return@runCatching null
        val ingredients = recipeRepository.getIngredientsForRecipe(recipeId); val steps = recipeRepository.getStepsForRecipe(recipeId); LoadedGraph(recipe, ingredients, steps, recipeRepository.getIngredientLinksForSteps(steps.map { it.id }))
    }.onSuccess { graph ->
        if (graph == null) { _uiState.update { it.copy(isLoading = false, notFound = true) }; return@onSuccess }
        originalRecipe = graph.recipe; originalStepsById = graph.steps.associateBy { it.id }; val linksByStep = graph.links.groupBy { it.stepId }
        _uiState.update { it.copy(isLoading = false, recipeId = graph.recipe.id, title = graph.recipe.title, description = graph.recipe.description.orEmpty(), servings = graph.recipe.servings?.toString().orEmpty(), prepTimeMinutes = graph.recipe.prepTimeMinutes?.toString().orEmpty(), cookTimeMinutes = graph.recipe.cookTimeMinutes?.toString().orEmpty(), recipeType = RecipeType.entries.firstOrNull { type -> type.name == graph.recipe.recipeType } ?: RecipeType.FULL_DISH, notes = graph.recipe.notes.orEmpty(), ingredients = graph.ingredients.map { ingredient -> IngredientInputState(localId = ingredient.id, query = ingredient.nameSnapshot, selectedIngredientId = ingredient.ingredientId, selectedIngredientDisplayName = ingredient.nameSnapshot.takeIf { ingredient.ingredientId != null }, quantityText = ingredient.quantityText.orEmpty(), unit = ingredient.unit.orEmpty(), prepNote = ingredient.prepNote.orEmpty(), section = ingredient.section.orEmpty(), optional = ingredient.optional) }, steps = graph.steps.map { step -> val timer = step.timerSeconds.toTimerInputs(); StepInputState(localId = step.id, instruction = step.instruction, timerMinutes = timer.first, timerSeconds = timer.second, warning = step.warning.orEmpty(), equipment = step.equipment.orEmpty(), whileTimerRuns = step.whileTimerRuns.orEmpty(), checkpoint = !step.checkpoint.isNullOrBlank(), linkedIngredientLocalIds = linksByStep[step.id].orEmpty().map { link -> link.recipeIngredientId }.toSet()) }, hasUnsavedChanges = false) }
    }.onFailure { throwable -> _uiState.update { it.copy(isLoading = false, saveError = throwable.message ?: "Recipe could not be loaded.") } } }

    fun updateTitle(value: String) = markChanged { it.copy(title = value, titleError = null, saveError = null) }; fun updateDescription(value: String) = markChanged { it.copy(description = value) }; fun updateServings(value: String) = markChanged { it.copy(servings = value, servingsError = null) }; fun updatePrepTimeMinutes(value: String) = markChanged { it.copy(prepTimeMinutes = value, prepTimeError = null) }; fun updateCookTimeMinutes(value: String) = markChanged { it.copy(cookTimeMinutes = value, cookTimeError = null) }; fun updateRecipeType(value: RecipeType) = markChanged { it.copy(recipeType = value) }; fun updateNotes(value: String) = markChanged { it.copy(notes = value) }
    fun addIngredientRow() = markChanged { it.copy(ingredients = it.ingredients + IngredientInputState(), ingredientError = null) }
    fun removeIngredientRow(localId: String) { searchJobs.remove(localId)?.cancel(); markChanged { state -> state.copy(ingredients = state.ingredients.filterNot { it.localId == localId }, steps = state.steps.map { it.copy(linkedIngredientLocalIds = it.linkedIngredientLocalIds - localId) }, ingredientError = null) } }
    fun updateIngredientQuery(localId: String, value: String) { markChanged { state -> state.copy(ingredients = state.ingredients.map { ingredient -> if (ingredient.localId != localId) ingredient else { val matches = value.trim() == ingredient.selectedIngredientDisplayName; ingredient.copy(query = value, selectedIngredientId = ingredient.selectedIngredientId.takeIf { matches }, selectedIngredientDisplayName = ingredient.selectedIngredientDisplayName.takeIf { matches }, suggestions = if (value.isBlank()) emptyList() else ingredient.suggestions, isSearching = value.isNotBlank()) } }, ingredientError = null) }; searchJobs.remove(localId)?.cancel(); if (value.isBlank()) { _uiState.updateIngredient(localId) { it.copy(suggestions = emptyList(), isSearching = false) }; return }; val job = viewModelScope.launch { val suggestions = ingredientRepository.searchIngredients(value, IngredientSuggestionLimit); _uiState.updateIngredient(localId) { if (it.query == value) it.copy(suggestions = suggestions, isSearching = false) else it } }; searchJobs[localId] = job; job.invokeOnCompletion { if (searchJobs[localId] == job) searchJobs.remove(localId) } }
    fun selectIngredient(localId: String, ingredient: IngredientEntity) = markIngredient(localId) { it.copy(query = ingredient.displayName, selectedIngredientId = ingredient.id, selectedIngredientDisplayName = ingredient.displayName, suggestions = emptyList(), unit = it.unit.ifBlank { ingredient.defaultUnit.orEmpty() }, isSearching = false) }
    fun updateQuantity(localId: String, value: String) = markIngredient(localId) { it.copy(quantityText = value) }; fun updateUnit(localId: String, value: String) = markIngredient(localId) { it.copy(unit = value) }; fun updatePrepNote(localId: String, value: String) = markIngredient(localId) { it.copy(prepNote = value) }; fun updateSection(localId: String, value: String) = markIngredient(localId) { it.copy(section = value) }; fun updateOptional(localId: String, value: Boolean) = markIngredient(localId) { it.copy(optional = value) }
    fun addStep() = markChanged { it.copy(steps = it.steps + StepInputState(), stepError = null) }; fun removeStep(localId: String) = markChanged { it.copy(steps = it.steps.filterNot { step -> step.localId == localId }, stepError = null) }; fun moveStepUp(localId: String) = markChanged { it.copy(steps = it.steps.moveItem(localId, -1), stepError = null) }; fun moveStepDown(localId: String) = markChanged { it.copy(steps = it.steps.moveItem(localId, 1), stepError = null) }
    fun updateStepInstruction(localId: String, value: String) = markStep(localId) { it.copy(instruction = value) }; fun updateStepTimerMinutes(localId: String, value: String) = markStep(localId) { it.copy(timerMinutes = value) }; fun updateStepTimerSeconds(localId: String, value: String) = markStep(localId) { it.copy(timerSeconds = value) }; fun updateStepWarning(localId: String, value: String) = markStep(localId) { it.copy(warning = value) }; fun updateStepEquipment(localId: String, value: String) = markStep(localId) { it.copy(equipment = value) }; fun updateStepWhileTimerRuns(localId: String, value: String) = markStep(localId) { it.copy(whileTimerRuns = value) }; fun updateStepCheckpoint(localId: String, value: Boolean) = markStep(localId) { it.copy(checkpoint = value) }
    fun toggleStepIngredientLink(stepLocalId: String, ingredientLocalId: String) = markStep(stepLocalId) { val links = it.linkedIngredientLocalIds; it.copy(linkedIngredientLocalIds = if (ingredientLocalId in links) links - ingredientLocalId else links + ingredientLocalId) }

    fun saveRecipe() {
        if (uiState.value.isSaving) return; val state = uiState.value; val recipe = originalRecipe ?: run { _uiState.update { it.copy(notFound = true) }; return }; val trimmedTitle = state.title.trim(); val servings = state.servings.parsePositiveIntOrNull(); val prep = state.prepTimeMinutes.parsePositiveIntOrNull(); val cook = state.cookTimeMinutes.parsePositiveIntOrNull(); val ingredientValidationError = state.ingredients.any { it.query.isBlank() && it.hasAnyIngredientDetail() }; val nonBlankSteps = state.steps.filterNot { it.isBlankStep() }; val stepInstructionError = nonBlankSteps.any { it.instruction.isBlank() }; val timerMinutesError = nonBlankSteps.any { step -> step.timerMinutes.trim().takeIf(String::isNotBlank)?.toIntOrNull()?.let { it < 0 } ?: step.timerMinutes.isNotBlank() }; val timerSecondsError = nonBlankSteps.any { step -> step.timerSeconds.trim().takeIf(String::isNotBlank)?.toIntOrNull()?.let { it !in 0..59 } ?: step.timerSeconds.isNotBlank() }
        _uiState.update { it.copy(titleError = if (trimmedTitle.isBlank()) "Recipe name is required." else null, servingsError = if (state.servings.isNotBlank() && servings == null) "Servings must be a number." else null, prepTimeError = if (state.prepTimeMinutes.isNotBlank() && prep == null) "Prep time must be minutes." else null, cookTimeError = if (state.cookTimeMinutes.isNotBlank() && cook == null) "Cook time must be minutes." else null, ingredientError = if (ingredientValidationError) "Each ingredient needs a name." else null, stepError = when { stepInstructionError -> "Each step needs an instruction."; timerMinutesError -> "Timer minutes must be a number."; timerSecondsError -> "Timer seconds must be 0–59."; else -> null }, saveError = null) }
        if (trimmedTitle.isBlank() || (state.servings.isNotBlank() && servings == null) || (state.prepTimeMinutes.isNotBlank() && prep == null) || (state.cookTimeMinutes.isNotBlank() && cook == null) || ingredientValidationError || stepInstructionError || timerMinutesError || timerSecondsError) return
        _uiState.update { it.copy(isSaving = true, saveError = null) }; viewModelScope.launch { runCatching { val updatedRecipe = recipe.copy(title = trimmedTitle, description = state.description.trimmedOrNull(), servings = servings, prepTimeMinutes = prep, cookTimeMinutes = cook, recipeType = state.recipeType.name, notes = state.notes.trimmedOrNull(), updatedAt = System.currentTimeMillis()); val ingredients = state.ingredients.filter { it.query.isNotBlank() }.mapIndexed { index, row -> val name = row.selectedIngredientDisplayName.takeIf { row.query.trim() == it } ?: row.query.trim(); val quantityText = row.quantityText.trimmedOrNull(); RecipeIngredientEntity(row.localId, recipe.id, row.selectedIngredientId.takeIf { row.query.trim() == row.selectedIngredientDisplayName }, name, quantityText?.toDoubleOrNull(), quantityText, row.unit.trimmedOrNull(), row.prepNote.trimmedOrNull(), row.section.trimmedOrNull(), row.optional, index) }; val savedIngredientIds = ingredients.map { it.id }.toSet(); val stepsWithInput = nonBlankSteps.mapIndexed { index, row -> val originalStep = originalStepsById[row.localId]; row to RecipeStepEntity(row.localId, recipe.id, row.instruction.trim(), row.parsedTimerSeconds(), originalStep?.temperatureValue, originalStep?.temperatureUnit, if (row.checkpoint) "Checkpoint" else null, row.warning.trimmedOrNull(), row.equipment.trimmedOrNull(), row.whileTimerRuns.trimmedOrNull(), index) }; val links = stepsWithInput.flatMap { (inputStep, savedStep) -> inputStep.linkedIngredientLocalIds.filter { it in savedIngredientIds }.map { StepIngredientLinkEntity(savedStep.id, it) } }; /* Components are not user-facing yet; when component editing ships, this screen must preserve/edit them instead of passing emptyList(). */ recipeRepository.saveRecipeGraph(updatedRecipe, ingredients, emptyList(), stepsWithInput.map { it.second }, links) }.onSuccess { _uiState.update { it.copy(isSaving = false, hasUnsavedChanges = false, saved = true) } }.onFailure { throwable -> _uiState.update { it.copy(isSaving = false, saveError = throwable.message ?: "Recipe could not be saved.") } } }
    }
    private fun markChanged(transform: (EditRecipeUiState) -> EditRecipeUiState) = _uiState.update { transform(it).copy(hasUnsavedChanges = true, saved = false) }; private fun markIngredient(localId: String, transform: (IngredientInputState) -> IngredientInputState) = markChanged { state -> state.copy(ingredients = state.ingredients.map { if (it.localId == localId) transform(it) else it }, ingredientError = null) }; private fun markStep(localId: String, transform: (StepInputState) -> StepInputState) = markChanged { state -> state.copy(steps = state.steps.map { if (it.localId == localId) transform(it) else it }, stepError = null) }
}
class EditRecipeViewModelFactory(private val recipeId: String, private val recipeRepository: RecipeRepository, private val ingredientRepository: IngredientRepository) : ViewModelProvider.Factory { @Suppress("UNCHECKED_CAST") override fun <T : ViewModel> create(modelClass: Class<T>): T { if (modelClass.isAssignableFrom(EditRecipeViewModel::class.java)) return EditRecipeViewModel(recipeId, recipeRepository, ingredientRepository) as T; throw IllegalArgumentException("Unknown ViewModel class: ${modelClass.name}") } }
private data class LoadedGraph(val recipe: RecipeEntity, val ingredients: List<RecipeIngredientEntity>, val steps: List<RecipeStepEntity>, val links: List<StepIngredientLinkEntity>)
private fun MutableStateFlow<EditRecipeUiState>.updateIngredient(localId: String, transform: (IngredientInputState) -> IngredientInputState) = update { state -> state.copy(ingredients = state.ingredients.map { if (it.localId == localId) transform(it) else it }) }
private fun String.trimmedOrNull(): String? = trim().takeIf { it.isNotBlank() }; private fun String.parsePositiveIntOrNull(): Int? = trim().takeIf { it.isNotBlank() }?.toIntOrNull()?.takeIf { it > 0 }; private fun IngredientInputState.hasAnyIngredientDetail(): Boolean = quantityText.isNotBlank() || unit.isNotBlank() || prepNote.isNotBlank() || section.isNotBlank() || optional
private fun List<StepInputState>.moveItem(localId: String, direction: Int): List<StepInputState> { val currentIndex = indexOfFirst { it.localId == localId }; if (currentIndex == -1) return this; val targetIndex = (currentIndex + direction).coerceIn(indices); if (targetIndex == currentIndex) return this; return toMutableList().also { val item = it.removeAt(currentIndex); it.add(targetIndex, item) } }
private fun StepInputState.isBlankStep(): Boolean = instruction.isBlank() && timerMinutes.isBlank() && timerSeconds.isBlank() && warning.isBlank() && equipment.isBlank() && whileTimerRuns.isBlank() && !checkpoint && linkedIngredientLocalIds.isEmpty(); private fun StepInputState.parsedTimerSeconds(): Int? { val minutes = timerMinutes.trim().takeIf { it.isNotBlank() }?.toIntOrNull() ?: 0; val seconds = timerSeconds.trim().takeIf { it.isNotBlank() }?.toIntOrNull() ?: 0; return (minutes * 60 + seconds).takeIf { it > 0 } }
private fun Int?.toTimerInputs(): Pair<String, String> = when { this == null || this <= 0 -> "" to ""; this < 60 -> "" to toString(); this % 60 == 0 -> (this / 60).toString() to ""; else -> (this / 60).toString() to (this % 60).toString() }
